In [1]:
import numpy as np

# 创建

In [6]:
score= np.array([[80,89,86,67,79],
                [78,97,89,67,81],
                [90,94,78,67,74],
                [91,91,90,67,69],
                [76,87,75,67,86],
                [70,79,84,67,84],
                [94,92,93,67,64],
                [86,85,83,67,80]])


# 效率对比

In [9]:
import time
import random

a=[]
for i in range(100000000):
    a.append(random.random())
%time sum1=sum(a)
a2=np.array(a)
%time sum2=np.sum(a2)

Wall time: 885 ms
Wall time: 180 ms


# ndarry的属性

In [11]:
score.shape # 返回一个数组维度的元组

(8, 5)

In [14]:
score.ndim #返回数组维数

2

In [16]:
score.size #返回数组中元素数量

40

In [17]:
score.itemsize # 返回一个元素的长度 （字节）

4

In [18]:
score.dtype #返回数组元素的类型

dtype('int32')

# 生成数组

## 生成纯0或1的数组

In [29]:
zero=np.zeros([3,4])
print("zero=",zero)
zero2=np.zeros_like(score)
print("zero2=",zero2)
one=np.ones([2,3])
print("one=",one)
one2=np.ones_like(score)
print("one2=",one2)

zero= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zero2= [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
one= [[1. 1. 1.]
 [1. 1. 1.]]
one2= [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 拷贝数组

In [30]:
arr=np.array([1,2,3,4,5])
arr1=np.array(arr) #深度拷贝
arr2=np.asarray(arr) #浅拷贝
arr[1]=10
print("arr1=",arr1," arr2=",arr2)

arr1= [1 2 3 4 5]  arr2= [ 1 10  3  4  5]


## 间隔生成数据

In [35]:
# 生成等间距数据
np.linspace(0,100,10) #从0到10 生成10个数据，包含头尾, (start起始，stop终止，num个数，endpoint=True是否包含末尾)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [36]:
np.arange(10,50,2)# 从10 到50 每间隔2个数生成一个 包含头不包含末尾

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [40]:
#生成log间隔数据
np.logspace(0,9,5)#以10为底 10^0到10^9为指数生成5个数字，包含头尾（start起始，stop末尾，num个数，endpoint=True是否包含末尾，base=10底数 

array([1.00000000e+00, 1.77827941e+02, 3.16227766e+04, 5.62341325e+06,
       1.00000000e+09])

## 生成随机数据

暂时留空