In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[13,14,15,16], [17,18,19,20], [21,22,23,24]]])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [5]:
a = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[13,14,15,16], [17,18,19,20], [21,22,23,24]]])
print(a.shape)

(2, 3, 4)


## 生成区间数组

In [6]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

## 生成区间均匀间隔数组

In [9]:
np.linspace(1, 15, 10, endpoint=True)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [10]:
np.linspace(1, 15, 5, endpoint=False)

array([ 1. ,  3.8,  6.6,  9.4, 12.2])

# 生成全0数组

In [11]:
np.zeros((10,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 生成区间全1数组

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# 按照第k对角线生成数组

```python
numpy.eye(N, M=None, k=0, dtype=<type 'float'>)
```
- N：输出数组的行数。
- M：输出数组的列数。
- k：对角线索引：0（默认）是指主对角线，正值是指上对角线，负值是指下对角线。

In [14]:
np.eye(5, 4, 0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [15]:
np.eye(5,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.eye(5,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(5,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 数组属性

In [20]:
a = np.array([[1,2,3], [4,5,6]])
print(a.shape)
print(a.dtype)
print(a.size)

(2, 3)
int64
6


## 数组重设

In [21]:
# 改变数组形状
a= np.zeros((2, 10))
np.reshape(a, (4, 5)) #需要保证转换后个数一致

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# 数组展开
a = np.arange(10).reshape((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.ravel(a) # 按照行拼接成一维数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.ravel(a, order='F') # 按照列拼接成一维数组

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [26]:
# 数组转置
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.transpose(a)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [31]:
# 数组连接
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
c = np.array([[11, 12]])
np.concatenate((a, b, c), axis=0)# 按照列连接

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
c = np.array([[16, 17, 18, 19], [20, 21, 22, 23], [24, 25, 26, 27]])
np.concatenate((a, b, c), axis=1)# 按照行连接

array([[ 1,  2,  7,  8,  9, 16, 17, 18, 19],
       [ 3,  4, 10, 11, 12, 20, 21, 22, 23],
       [ 5,  6, 13, 14, 15, 24, 25, 26, 27]])

In [34]:
#改变数组尺寸
a = np.arange(10)
a.resize(2,5)# resize是对原数组进行重整，reshape是拷贝了一份新数组
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 数组索引和切片

In [37]:
#数组索引
a = np.arange(10) # 生成 0-9
print(a[1])
print(a[[1,3,6]])
b = np.arange(20).reshape(4,5)
print(b[1,3])

1
[1 3 6]
8


In [38]:
#数组切片
f = np.arange(10)
f[:3]

array([0, 1, 2])

In [39]:
f[5:10]

array([5, 6, 7, 8, 9])

In [40]:
g = np.arange(20).reshape(4,5)
g[:3,1:2]

array([[ 1],
       [ 6],
       [11]])